# Generated by Django 5.2 on 2025-04-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comcol_backend', '0003_alter_computer_description_alter_computer_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
