# Generated by Django 5.2 on 2025-04-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maker', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='computer_pictures/')),
            ],
        ),
    ]
