# Generated by Django 5.2 on 2025-04-13 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comcol_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='pictures',
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='computer_pictures/')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='comcol_backend.computer')),
            ],
        ),
    ]
