# Generated by Django 5.2 on 2025-04-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comcol_backend', '0005_alter_computer_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
