# Generated by Django 5.2 on 2025-04-17 09:36

import comcol_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comcol_backend', '0006_picture_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='extension',
            field=models.CharField(default='jpeg', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='picture',
            name='unique_id',
            field=models.CharField(db_index=True, default=42, editable=False, max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=comcol_backend.models.picture_upload_to),
        ),
    ]
