# Generated by Django 5.2 on 2025-04-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comcol_backend', '0008_computer_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='favorite',
            field=models.TextField(blank=True, default=''),
        ),
    ]
